"""add dynamic fields

Revision ID: 25311a20122f
Revises: f5e25cca85cf
Create Date: 2026-06-25 18:27:44.743728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25311a20122f'
down_revision: Union[str, Sequence[str], None] = 'f5e25cca85cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('market_cap', sa.BigInteger(), nullable=True))
    op.add_column('assets', sa.Column('universe_name', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('universe_rank', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('assets', sa.Column('data_source', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('last_universe_update', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_assets_universe_name'), 'assets', ['universe_name'], unique=False)
    op.create_index(op.f('ix_assets_universe_rank'), 'assets', ['universe_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_universe_rank'), table_name='assets')
    op.drop_index(op.f('ix_assets_universe_name'), table_name='assets')
    op.drop_column('assets', 'last_universe_update')
    op.drop_column('assets', 'data_source')
    op.drop_column('assets', 'is_active')
    op.drop_column('assets', 'universe_rank')
    op.drop_column('assets', 'universe_name')
    op.drop_column('assets', 'market_cap')
    op.drop_column('assets', 'country')
    # ### end Alembic commands ###
