"""Create daily features table

Revision ID: 6fdfb6e2e7d8
Revises: 25311a20122f
Create Date: 2026-06-25 19:30:54.692686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdfb6e2e7d8'
down_revision: Union[str, Sequence[str], None] = '25311a20122f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('log_return', sa.Float(), nullable=True),
    sa.Column('volume_change', sa.Float(), nullable=True),
    sa.Column('volatility_7d', sa.Float(), nullable=True),
    sa.Column('volatility_30d', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('distance_from_sma_20', sa.Float(), nullable=True),
    sa.Column('distance_from_sma_200', sa.Float(), nullable=True),
    sa.Column('momentum_7d', sa.Float(), nullable=True),
    sa.Column('momentum_30d', sa.Float(), nullable=True),
    sa.Column('momentum_90d', sa.Float(), nullable=True),
    sa.Column('drawdown_252d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_feature_asset_date')
    )
    op.create_index(op.f('ix_features_daily_asset_id'), 'features_daily', ['asset_id'], unique=False)
    op.create_index(op.f('ix_features_daily_date'), 'features_daily', ['date'], unique=False)
    op.create_index(op.f('ix_features_daily_id'), 'features_daily', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_daily_id'), table_name='features_daily')
    op.drop_index(op.f('ix_features_daily_date'), table_name='features_daily')
    op.drop_index(op.f('ix_features_daily_asset_id'), table_name='features_daily')
    op.drop_table('features_daily')
    # ### end Alembic commands ###
