"""Create daily targets table

Revision ID: b2dd79b4d35f
Revises: 6fdfb6e2e7d8
Create Date: 2026-06-27 13:16:15.343095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dd79b4d35f'
down_revision: Union[str, Sequence[str], None] = '6fdfb6e2e7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('future_return_1d', sa.Float(), nullable=True),
    sa.Column('future_return_7d', sa.Float(), nullable=True),
    sa.Column('future_return_30d', sa.Float(), nullable=True),
    sa.Column('future_return_90d', sa.Float(), nullable=True),
    sa.Column('future_return_180d', sa.Float(), nullable=True),
    sa.Column('future_return_252d', sa.Float(), nullable=True),
    sa.Column('future_direction_1d', sa.Integer(), nullable=True),
    sa.Column('future_direction_7d', sa.Integer(), nullable=True),
    sa.Column('future_direction_30d', sa.Integer(), nullable=True),
    sa.Column('future_direction_90d', sa.Integer(), nullable=True),
    sa.Column('future_direction_180d', sa.Integer(), nullable=True),
    sa.Column('future_direction_252d', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_target_asset_date')
    )
    op.create_index(op.f('ix_targets_daily_asset_id'), 'targets_daily', ['asset_id'], unique=False)
    op.create_index(op.f('ix_targets_daily_date'), 'targets_daily', ['date'], unique=False)
    op.create_index(op.f('ix_targets_daily_id'), 'targets_daily', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targets_daily_id'), table_name='targets_daily')
    op.drop_index(op.f('ix_targets_daily_date'), table_name='targets_daily')
    op.drop_index(op.f('ix_targets_daily_asset_id'), table_name='targets_daily')
    op.drop_table('targets_daily')
    # ### end Alembic commands ###
