"""Create journal entries table

Revision ID: b4092695b34a
Revises: de3e0b715b08
Create Date: 2026-06-30 00:34:06.153008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4092695b34a'
down_revision: Union[str, Sequence[str], None] = 'de3e0b715b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_asset_id'), 'journal_entries', ['asset_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_horizon_days'), 'journal_entries', ['horizon_days'], unique=False)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_horizon_days'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_asset_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
