"""Create horizon targets table

Revision ID: de3e0b715b08
Revises: 5e39c974489d
Create Date: 2026-06-29 23:34:26.245226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3e0b715b08'
down_revision: Union[str, Sequence[str], None] = '5e39c974489d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets_horizon_daily',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('future_return', sa.Float(), nullable=True),
    sa.Column('future_direction', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', 'horizon_days', name='uq_targets_horizon_daily_asset_date_horizon')
    )
    op.create_index(op.f('ix_targets_horizon_daily_asset_id'), 'targets_horizon_daily', ['asset_id'], unique=False)
    op.create_index(op.f('ix_targets_horizon_daily_date'), 'targets_horizon_daily', ['date'], unique=False)
    op.create_index('ix_targets_horizon_daily_horizon_date', 'targets_horizon_daily', ['horizon_days', 'date'], unique=False)
    op.create_index(op.f('ix_targets_horizon_daily_horizon_days'), 'targets_horizon_daily', ['horizon_days'], unique=False)
    op.create_index(op.f('ix_targets_horizon_daily_id'), 'targets_horizon_daily', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targets_horizon_daily_id'), table_name='targets_horizon_daily')
    op.drop_index(op.f('ix_targets_horizon_daily_horizon_days'), table_name='targets_horizon_daily')
    op.drop_index('ix_targets_horizon_daily_horizon_date', table_name='targets_horizon_daily')
    op.drop_index(op.f('ix_targets_horizon_daily_date'), table_name='targets_horizon_daily')
    op.drop_index(op.f('ix_targets_horizon_daily_asset_id'), table_name='targets_horizon_daily')
    op.drop_table('targets_horizon_daily')
    # ### end Alembic commands ###
